version: '2'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=db_api
  nodejs:
    build: .
    container_name: cicd-api
    restart: always
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      - DB_HOST=postgres
      - DB_USER=developer
      - DB_PASS=qwerty
      - DB_NAME=db_api
